import { NextResponse } from "next/server";
import OpenAI from "openai";
import { prisma } from "@/lib/prisma";
import { auth } from "@clerk/nextjs/server";

const openai = new OpenAI({
  apiKey: process.env.OPENAI_API_KEY,
});

export async function POST(req: Request) {
  try {
    const { userId } = await auth();
    if (!userId) {
      return new NextResponse("Unauthorized", { status: 401 });
    }

    const { topic } = await req.json();
    if (!topic) {
      return new NextResponse("Topic is required", { status: 400 });
    }

    // Check if roadmap already exists to save API costs
    const existingRoadmap = await prisma.roadmap.findUnique({
      where: { topic: topic.toLowerCase() },
    });

    if (existingRoadmap) {
      return NextResponse.json(existingRoadmap);
    }

    // Call OpenAI
    const response = await openai.chat.completions.create({
      model: "gpt-4o-mini",
      messages: [
        {
          role: "system",
          content: `You are an expert curriculum designer. 
Generate a detailed learning roadmap for the given topic. 
Return ONLY a valid JSON object with this exact structure:
{
  "nodes": [
    { "id": "1", "position": { "x": 400, "y": 0 }, "data": { "label": "Topic Name" }, "type": "input" },
    { "id": "2", "position": { "x": 200, "y": 150 }, "data": { "label": "Subtopic 1" } },
    { "id": "3", "position": { "x": 600, "y": 150 }, "data": { "label": "Subtopic 2" } }
  ],
  "edges": [
    { "id": "e1-2", "source": "1", "target": "2", "animated": true },
    { "id": "e1-3", "source": "1", "target": "3", "animated": true }
  ],
  "description": "A short 1-2 sentence summary of this learning path."
}
Use 6-10 nodes. Spread them out vertically (y: 0, 150, 300, 450...) so they don't overlap. Make the last node type "output".`,
        },
        {
          role: "user",
          content: `Generate a roadmap for: ${topic}`,
        },
      ],
      response_format: { type: "json_object" },
    });

    const aiContent = response.choices[0].message.content;
    if (!aiContent) {
      throw new Error("Failed to generate content from OpenAI");
    }

    const parsedContent = JSON.parse(aiContent);

    // Save to Database
    const newRoadmap = await prisma.roadmap.create({
      data: {
        title: `${topic} Roadmap`,
        topic: topic.toLowerCase(),
        description: parsedContent.description || "Generated by SkillMapAi",
        nodes: parsedContent.nodes,
        edges: parsedContent.edges,
        authorId: userId,
      },
    });

    return NextResponse.json(newRoadmap);
  } catch (error: any) {
    console.error("[ROADMAP_GENERATE_ERROR]", error);
    
    // Check if it's an OpenAI error
    if (error?.status === 429 || error?.code === 'insufficient_quota') {
      return new NextResponse(
        "OpenAI API quota exceeded. Please check your OpenAI billing details.",
        { status: 429 }
      );
    }
    
    if (error?.message) {
      return new NextResponse(error.message, { status: 500 });
    }

    return new NextResponse("Internal Error", { status: 500 });
  }
}
