import { NextResponse } from "next/server";
import Groq from "groq-sdk";
import { prisma } from "@/lib/prisma";
import { auth, currentUser } from "@clerk/nextjs/server";

// Initialize Groq API for Llama 3.1
const groq = new Groq({ apiKey: process.env.GROQ_API_KEY || "" });

export async function POST(req: Request) {
  try {
    const { userId } = await auth();
    const clerkUser = await currentUser();

    if (!userId || !clerkUser) {
      return new NextResponse("Unauthorized", { status: 401 });
    }

    // Ensure the user exists in our DB to prevent foreign key errors
    const dbUser = await prisma.user.upsert({
      where: { userId },
      update: {},
      create: {
        userId: userId,
        email: clerkUser.emailAddresses[0]?.emailAddress || "",
        name: `${clerkUser.firstName || ''} ${clerkUser.lastName || ''}`.trim() || "Anonymous",
        imageUrl: clerkUser.imageUrl,
      },
    });

    const { topic } = await req.json();
    if (!topic) {
      return new NextResponse("Topic is required", { status: 400 });
    }

    // Check if roadmap already exists to save API costs
    const existingRoadmap = await prisma.roadmap.findUnique({
      where: { topic: topic.toLowerCase() },
    });

    if (existingRoadmap) {
      return NextResponse.json(existingRoadmap);
    }

    if (!process.env.GROQ_API_KEY || process.env.GROQ_API_KEY === "your_groq_api_key_here") {
      return new NextResponse("Llama/Groq API key is missing. Please add GROQ_API_KEY to your .env file.", { status: 400 });
    }

    const prompt = `
You are an expert curriculum designer. 
Generate a detailed learning roadmap for the given topic: "${topic}". 
Return ONLY a valid JSON object with this exact structure:
{
  "nodes": [
    { "id": "1", "position": { "x": 400, "y": 0 }, "data": { "label": "Topic Name" }, "type": "input" },
    { "id": "2", "position": { "x": 200, "y": 150 }, "data": { "label": "Subtopic 1" } },
    { "id": "3", "position": { "x": 600, "y": 150 }, "data": { "label": "Subtopic 2" } }
  ],
  "edges": [
    { "id": "e1-2", "source": "1", "target": "2", "animated": true },
    { "id": "e1-3", "source": "1", "target": "3", "animated": true }
  ],
  "description": "A short 1-2 sentence summary of this learning path."
}
Use 6-10 nodes. Spread them out vertically (y: 0, 150, 300, 450...) so they don't overlap. Make the last node type "output".
`;

    // Call Groq API with Llama 3.1
    const chatCompletion = await groq.chat.completions.create({
      messages: [
        {
          role: "system",
          content: "You are a JSON generator. You always return perfect, parseable JSON and nothing else."
        },
        {
          role: "user",
          content: prompt
        }
      ],
      model: "llama-3.1-8b-instant",
      response_format: { type: "json_object" },
    });

    let aiContent = chatCompletion.choices[0]?.message?.content || "";
    aiContent = aiContent.trim();

    if (!aiContent) {
      throw new Error("Failed to generate content from Llama 3.1");
    }

    const parsedContent = JSON.parse(aiContent);

    // Save to Database
    const newRoadmap = await prisma.roadmap.create({
      data: {
        title: `${topic} Roadmap`,
        topic: topic.toLowerCase(),
        description: parsedContent.description || "Generated by SkillMapAi",
        nodes: parsedContent.nodes,
        edges: parsedContent.edges,
        authorId: dbUser.id,
      },
    });

    return NextResponse.json(newRoadmap);
  } catch (error: any) {
    console.error("[ROADMAP_GENERATE_ERROR]", error);

    if (error?.status === 401) {
      return new NextResponse("Invalid Llama API key. Please check your credentials.", { status: 401 });
    }

    if (error?.message) {
      return new NextResponse(error.message, { status: 500 });
    }

    return new NextResponse("Internal Error", { status: 500 });
  }
}
