"use client";

import Link from "next/link";
import { Button } from "@/components/ui/button";
import { motion, useInView } from "framer-motion";
import {
  BrainCircuit,
  ArrowRight,
  Sparkles,
  Map,
  BookOpen,
  Target,
  Zap,
  GraduationCap,
} from "lucide-react";
import { UserButton, useAuth } from "@clerk/nextjs";
import { useRef } from "react";

import { AuroraBackground } from "@/components/landing/AuroraBackground";
import { ParticleField } from "@/components/landing/ParticleField";
import { AnimatedText } from "@/components/landing/AnimatedText";
import { AnimatedSearch } from "@/components/landing/AnimatedSearch";
import { FeatureCard } from "@/components/landing/FeatureCard";
import { HowItWorks } from "@/components/landing/HowItWorks";
import { Footer } from "@/components/landing/Footer";

const FEATURES = [
  {
    title: "AI-Powered Roadmaps",
    description:
      "Enter any topic and our AI instantly generates a structured, interactive visual learning path tailored to the skill.",
    icon: Map,
    accentColor: "#818cf8",
  },
  {
    title: "Curated Resources",
    description:
      "Every node comes packed with top-rated articles, tutorials, and documentation from GeeksforGeeks and beyond.",
    icon: BookOpen,
    accentColor: "#22d3ee",
  },
  {
    title: "Smart Progress Tracking",
    description:
      "Mark topics complete, save your favorite paths, and visualize your growth with real-time progress indicators.",
    icon: Target,
    accentColor: "#34d399",
  },
  {
    title: "Interview Preparation",
    description:
      "AI-generated interview questions for every topic, filtered by difficulty with detailed model answers.",
    icon: GraduationCap,
    accentColor: "#f59e0b",
  },
  {
    title: "Key Concepts & Notes",
    description:
      "Structured revision notes, core concept breakdowns, and common mistakes — all auto-generated by AI.",
    icon: Sparkles,
    accentColor: "#f472b6",
  },
  {
    title: "Instant Generation",
    description:
      "No waiting. Get a complete, interactive curriculum in seconds. Powered by advanced LLM technology.",
    icon: Zap,
    accentColor: "#a78bfa",
  },
];

export default function LandingPage() {
  const { isSignedIn } = useAuth();
  const featuresRef = useRef<HTMLDivElement>(null);
  const ctaRef = useRef<HTMLDivElement>(null);
  const featuresInView = useInView(featuresRef, { once: true, margin: "-50px" });
  const ctaInView = useInView(ctaRef, { once: true, margin: "-50px" });

  return (
    <div className="min-h-screen bg-black text-white selection:bg-indigo-500/30 selection:text-white overflow-x-hidden">
      {/* === BACKGROUND LAYERS === */}
      <AuroraBackground />
      <ParticleField />

      {/* === NAVBAR === */}
      <header className="fixed top-0 w-full z-50 bg-black/30 backdrop-blur-md">
        <div className="max-w-7xl mx-auto px-6 md:px-8 py-4 flex items-center justify-between">
          <div className="flex items-center gap-2.5">
            <div className="h-8 w-8 rounded-lg bg-indigo-500/20 flex items-center justify-center">
              <BrainCircuit className="h-4 w-4 text-indigo-400" />
            </div>
            <span className="text-base font-bold tracking-tight text-white/90">
              SkillMapAi
            </span>
          </div>
          <div className="flex items-center gap-3">
            {isSignedIn ? (
              <>
                <Link href="/dashboard">
                  <Button
                    variant="ghost"
                    className="text-white/70 hover:text-white hover:bg-white/10 text-sm rounded-xl h-9 px-4"
                  >
                    Dashboard
                  </Button>
                </Link>
                <UserButton />
              </>
            ) : (
              <>
                <Link href="/sign-in">
                  <Button
                    variant="ghost"
                    className="text-white/60 hover:text-white hover:bg-white/10 text-sm rounded-xl h-9 px-4"
                  >
                    Log in
                  </Button>
                </Link>
                <Link href="/sign-up">
                  <motion.button
                    whileHover={{ scale: 1.03 }}
                    whileTap={{ scale: 0.97 }}
                    className="h-9 px-5 rounded-xl bg-white text-black text-sm font-semibold hover:shadow-[0_0_20px_rgba(139,92,246,0.3)] transition-shadow duration-300"
                  >
                    Get Started
                  </motion.button>
                </Link>
              </>
            )}
          </div>
        </div>
      </header>

      {/* === HERO SECTION === */}
      <main className="relative z-10">
        <section className="pt-36 pb-8 md:pt-48 md:pb-16 px-4">
          <div className="container mx-auto max-w-5xl">
            <div className="flex flex-col items-center text-center space-y-6">
              {/* Badge */}
              <motion.div
                initial={{ opacity: 0, y: 15, filter: "blur(5px)" }}
                animate={{ opacity: 1, y: 0, filter: "blur(0px)" }}
                transition={{ duration: 0.5 }}
                className="inline-flex items-center gap-2 rounded-full border border-white/[0.08] bg-white/[0.03] px-4 py-1.5 text-xs text-white/60 backdrop-blur-sm"
              >
                <Sparkles className="h-3.5 w-3.5 text-indigo-400" />
                <span>Powered by AI — Generate roadmaps instantly</span>
              </motion.div>

              {/* Headline */}
              <h1 className="text-4xl sm:text-5xl md:text-7xl font-bold tracking-tight max-w-4xl leading-[1.15]">
                <motion.span
                  initial={{ opacity: 0, y: 20, filter: "blur(5px)" }}
                  animate={{ opacity: 1, y: 0, filter: "blur(0px)" }}
                  transition={{ duration: 0.6, delay: 0.2, ease: [0.25, 0.4, 0.25, 1] }}
                  className="text-white mr-4 inline-block"
                >
                  Master any skill with
                </motion.span>
                <br className="sm:hidden" />
                <motion.span
                  initial={{ opacity: 0, y: 20, filter: "blur(5px)" }}
                  animate={{ opacity: 1, y: 0, filter: "blur(0px)" }}
                  transition={{ duration: 0.6, delay: 0.5, ease: [0.25, 0.4, 0.25, 1] }}
                  className="text-gradient-hero inline-block"
                >
                  AI-powered roadmaps.
                </motion.span>
              </h1>

              {/* Subheadline */}
              <motion.p
                initial={{ opacity: 0, y: 20, filter: "blur(5px)" }}
                animate={{ opacity: 1, y: 0, filter: "blur(0px)" }}
                transition={{ duration: 0.6, delay: 1.0 }}
                className="text-sm md:text-lg text-white/40 max-w-2xl leading-relaxed"
              >
                Enter any topic and instantly get a visual learning path, curated
                resources, and AI-generated notes to accelerate your journey.
              </motion.p>

              {/* Search */}
              <AnimatedSearch isSignedIn={!!isSignedIn} />
            </div>
          </div>
        </section>

        {/* === FEATURES GRID === */}
        <section className="px-4 py-16 md:py-24" ref={featuresRef}>
          <div className="container mx-auto max-w-6xl">
            {/* Section header */}
            <motion.div
              initial={{ opacity: 0, y: 30 }}
              animate={featuresInView ? { opacity: 1, y: 0 } : {}}
              transition={{ duration: 0.6 }}
              className="text-center mb-12 md:mb-16"
            >
              <span className="text-xs uppercase tracking-[0.2em] text-white/40 font-medium">
                Features
              </span>
              <h2 className="text-3xl md:text-5xl font-bold mt-3 text-white/90">
                Everything you need to{" "}
                <span className="text-shimmer">learn faster</span>
              </h2>
            </motion.div>

            {/* Cards grid */}
            <div className="grid md:grid-cols-2 lg:grid-cols-3 gap-5">
              {FEATURES.map((feature, i) => (
                <FeatureCard
                  key={i}
                  title={feature.title}
                  description={feature.description}
                  icon={feature.icon}
                  index={i}
                  accentColor={feature.accentColor}
                />
              ))}
            </div>
          </div>
        </section>

        {/* === HOW IT WORKS === */}
        <section className="px-4">
          <div className="container mx-auto max-w-6xl">
            <HowItWorks />
          </div>
        </section>

        {/* === CTA SECTION === */}
        <section className="px-4 py-24 md:py-32" ref={ctaRef}>
          <div className="container mx-auto max-w-3xl text-center">
            <motion.div
              initial={{ opacity: 0, y: 30 }}
              animate={ctaInView ? { opacity: 1, y: 0 } : {}}
              transition={{ duration: 0.6 }}
              className="relative"
            >
              {/* Background glow */}
              <div
                className="absolute inset-0 -z-10"
                style={{
                  background:
                    "radial-gradient(ellipse at center, rgba(139,92,246,0.08) 0%, transparent 70%)",
                  filter: "blur(60px)",
                }}
              />

              <h2 className="text-3xl md:text-5xl font-bold text-white/90 mb-4">
                Ready to accelerate
                <br />
                your learning?
              </h2>
              <p className="text-white/40 mb-8 max-w-lg mx-auto text-sm md:text-base">
                Join thousands of learners who are mastering new skills with
                AI-powered roadmaps. It&apos;s free to get started.
              </p>
              <Link href={isSignedIn ? "/search" : "/sign-up"}>
                <motion.button
                  whileHover={{ scale: 1.04 }}
                  whileTap={{ scale: 0.97 }}
                  className="h-12 px-8 rounded-2xl bg-white text-black font-semibold text-sm gap-2 inline-flex items-center hover:shadow-[0_0_40px_rgba(139,92,246,0.3)] transition-shadow duration-500"
                >
                  {isSignedIn ? "Go to Dashboard" : "Get Started for Free"}
                  <ArrowRight className="h-4 w-4" />
                </motion.button>
              </Link>
            </motion.div>
          </div>
        </section>

        {/* === FOOTER === */}
        <Footer />
      </main>
    </div>
  );
}
